### ISSUE TITLE
Class not found: com.example.WebServerHttpApp

### ISSUE THREAD

**Issue by humblevladimirthegreat** [jeroenr/akka-http-docker-sample#1]
I am following your blog post located at https://medium.com/jeroen-rosenberg/lightweight-docker-containers-for-scala-apps-11b99cf1a666

After starting a new sbt project using the recommended command
 `sbt -Dsbt.version=0.13.15 new https://github.com/akka/akka-http-scala-seed.g8`

It successfully applies the template:
`name [My Akka HTTP Project]: hello-world`
`scala_version [2.12.3]: `
`akka_http_version [10.0.9]: `
`akka_version [2.5.3]: `
`organization [com.example]: `
`Template applied in ./hello-world`

I then try to start the service using 
`sbt "runMain com.example.WebServerHttpApp"`

but this yields error that it cannot find the specified class: 
`[error] (run-main-0) java.lang.ClassNotFoundException: com.example.WebServerHttpApp`
`java.lang.ClassNotFoundException: com.example.WebServerHttpApp`

Inspecting the src folder, indeed there is no package named com.example and all code appears to be under the package com.lightbend.akka.http.sample which contains 4 files, none of which are named WebServerHttpApp, and the one that seems to be a main-looking file is called QuickstartServer.scala but this does not have a Main method.

Perhaps the giter8 template has dramatically changed since the blog post 10 days ago? Interestingly, opening https://github.com/akka/akka-http-scala-seed.g8 in a browser redirects to https://github.com/akka/akka-http-quickstart-scala.g8

In case it matters, I am running Ubuntu 16.04 with sbt 0.13.15

**Comment by jeroenr** [comment]
Thanks for reporting this and apologies for not replying earlier! It does indeed seem that the giter8 template is radically changed. I'll update my post. To continue following the steps in the blog you'll need to change:

```sbt "runMain com.example.WebServerHttpApp"``` to ```sbt "runMain com.lightbend.akka.http.sample.QuickstartServer"```

and 

```curl localhost:8080/hello``` to ```curl localhost:8080/users```
